# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
FACEBOOK_APP_ID: "3185688561448220"
FACEBOOK_APP_SECRET: 93a6b97c5a1b4c69cda10f1ad542af2b
GOOGLE_APP_ID: 141639892621-04h27294q49juulr6i76q5f80touefvm.apps.googleusercontent.com
GOOGLE_APP_SECRET: o2uQq9eEWbRy1kT4p4hEpwk3
TWITTER_APP_ID: IFOdwEa90prAcVjd0qw1e9hYY
TWITTER_APP_SECRET: uSgu24x3aDbhGHgn7iUmVshrBnuaC8OeWfQxm6jbOWaqYN2PhE

